### ISSUE TITLE
In-place numpy function return assignment

### ISSUE THREAD

**Issue by ronpandolfi** [lbl-camera/fvGP#15]
In `gp.py`, `np.fill_diagonal` is used incorrectly. This function operates in-place with no return value.

https://github.com/lbl-camera/fvGP/blob/a09dee20088e4f79d716407691dddf3d08062294/fvgp/gp.py#L893

The above will only ever assign `None` to S.

I would submit a PR myself, but I'm also unclear on the meaning of `S(x)`. Could this also be documented?

**Comment by ronpandolfi** [comment]
Addressing this now in https://github.com/lbl-camera/fvGP/pull/16

**Comment by MarcusMNoack** [comment]
good catch! Seems like you fixed it. But as additional explanation: S is the full posterior covariance matrix, which, if everything goes well, has the variances along the diagonals. If we use the inverse of the prior covariance matrix and we are only interested in the variances (v instead of the full S), we can speed up the computation.
